export const OFFERLOADING = "OFFERLOADING";

export const OFFERFAILED = "OFFERFAILED";

export const ADDOFFERSUCCESS = "ADDOFFERSUCCESS";

export const GETALLOFFERSSUCCESS = "GETALLOFFERSSUCCESS";

export const GETALLOWNERS = "GETALLOWNERS";

export const ACCEPT_DECLINE_OFFER = "ACCEPT_DECLINE_OFFER";

export const DELETEOFFERSUCCESS = "DELETEOFFERSUCCESS";

export const GETUNIQUEOFFERS = "GETUNIQUEOFFERS";

export const OFFERCOMPLETED = "OFFERCOMPLETED";

