export const OFFERLOADING = "OFFERLOADING";

export const OFFERFAILED = "OFFERFAILED";

export const ADDOFFERSUCCESS = "ADDOFFERSUCCESS";

export const GETALLOFFERSSUCCESS = "GETALLOFFERSSUCCESS";

export const GETALLOWNERS = "GETALLOWNERS";
