export const PETLOADING = "PETLOADING";

export const PETFAILED = "PETFAILED";

export const GETALLPETSSUCCESS = "GETALLPETSSUCCESS";

export const GETONEPETSSUCCESS = "GETONEPETSSUCCESS";

export const ADDPETSUCCESS = "ADDPETSUCCESS";

export const EDITPETSUCCESS = "EDITPETSUCCESS"

export const DELETEPETSUCCESS = "DELETEPETSUCCESS"