export const PETLOADING = "PETLOADING";

export const FAILED = "FAILED";

export const GETALLPETSSUCCESS = "GETALLPETSSUCCESS";

export const GETONEPETSSUCCESS = "GETONEPETSSUCCESS";

export const ADDPETSUCCESS = "ADDPETSUCCESS";

export const EDITPETSUCCESS = "EDITPETSUCCESS"

export const DELETEPETSUCCESS = "DELETEPETSUCCESS"