export const ADDROOMSUCCESS = "ADDREVIEWSUCCESS";

export const ROOMLOADING = "ROOMLOADING";

export const ROOMFAILED = "ROOMFAILED";

export const GETALLMESSAGES = "GETALLMESSAGES";

export const PUSHMESSAGE = "PUSHMESSAGE";

export const DELETEROOMSUCCESS = "DELETEROOMSUCCESS";

export const CLEARMESSAGES = "CLEARMESSAGES";
