export const USERLOADING = "USERLOADING";

export const USERFAILED = "USERFAILED";

export const EDITUSER = "EDITUSER";

export const DELETEUSERSUCCESS = "DELETEUSERSUCCESS";

export const GETALLSITTERSSUCCESS="GETALLSITTERSSUCCESS"

export const RESETPASSWORD="RESETPASSWORD"

export const SENDRESETEMAIL="SENDRESETEMAIL"
